name: primevarclass-structural-engines
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pandas
  - numpy
  - scipy
  - rdkit
  - openbabel
  - xtb
  - psi4
  - openmm
  - pdbfixer
  - vina
  - pip
  - pip:
      - qiskit-nature
      - qiskit-algorithms
