# Generated by PrimeVarClass. Run only when you want to stream the official AlphaMissense table.
$ErrorActionPreference = 'Stop'
py -3.14 scripts\extract_alphamissense_subset.py `
  --alphamissense-input "https://storage.googleapis.com/dm_alphamissense/AlphaMissense_hg38.tsv.gz" `
  --targets "primevarclass_jovem_cientista_evidence_20260511\alphamissense_priority_enrichment\alphamissense_priority_coordinate_targets.csv" `
  --output "data\raw\alphamissense\target_gene_alphamissense.tsv"
