# Generated by PrimeVarClass. Protein-substitution extraction is preferred when VCF coordinates do not align.
$ErrorActionPreference = 'Stop'
py -3.14 scripts\extract_alphamissense_subset.py `
  --mode aa `
  --alphamissense-input "https://storage.googleapis.com/dm_alphamissense/AlphaMissense_aa_substitutions.tsv.gz" `
  --targets "primevarclass_jovem_cientista_evidence_20260511\alphamissense_priority_enrichment\alphamissense_priority_protein_targets.tsv" `
  --output "data\raw\alphamissense\target_gene_alphamissense.tsv"
