"""PrimeVarClass — domain-aware, externally validated classification of
BRCA1/BRCA2 missense variants of uncertain significance.

This package exposes the reproducible core used in the manuscript
(``docs/manuscrito/``):

* :mod:`primevarclass.domain_annotation` — curated UniProt functional-domain map
  (BRCA1 RING/BRCT; BRCA2 DBD), the anti-leakage feature at the heart of the model.
* :mod:`primevarclass.core` — feature engineering, training and validation
  (Random Forest), plus ACMG/AMP evidence-strength mapping.
* :mod:`primevarclass.esm_scores` — ingestion of zero-shot ESM-2 protein
  language-model scores (decoupled from training; no GPU required at inference).
* :mod:`primevarclass.data_sources` — ingestion of public sources
  (ClinVar, gnomAD, ENIGMA/ClinGen expert panels).

Every result and figure in the manuscript is regenerated by the scripts in
``scratch/`` from these modules and public data — nothing is hard-coded or mocked.
"""
from __future__ import annotations

from .core import (
    build_dataset_from_csv,
    build_dataset_from_dataframe,
    classify_acmg_strength_from_lr,
    encode_variant_features,
    get_feature_subsets,
    normalize_gene,
    normalize_label,
    parse_variant,
)
from .data_sources import (
    build_dataset_from_source_config,
    ingest_sources_from_config,
    train_from_source_config,
)
from .domain_annotation import annotate_domain
from .esm_scores import attach_esm_scores, build_esm_lookup, load_esm_scores

__version__ = "1.0.0"

__all__ = [
    "annotate_domain",
    "attach_esm_scores",
    "build_dataset_from_csv",
    "build_dataset_from_dataframe",
    "build_dataset_from_source_config",
    "build_esm_lookup",
    "classify_acmg_strength_from_lr",
    "encode_variant_features",
    "get_feature_subsets",
    "ingest_sources_from_config",
    "load_esm_scores",
    "normalize_gene",
    "normalize_label",
    "parse_variant",
    "train_from_source_config",
    "__version__",
]
