[study]
name = "PrimeVarClass Multigene ClinVar Benchmark"
mode = "hybrid"
high_confidence_only = false
keep_metadata = true
primary_metric = "auc_roc"
baseline_experiment = "external_predictors_only"
n_bootstrap = 80
consensus_top_k = 3
model_families = ["random_forest", "logistic_regression"]

[[cohorts]]
name = "multigene_training"
role = "train"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/multigene_training.toml"

[[cohorts]]
name = "multigene_combined_external_validation"
role = "external_test"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/multigene_combined_external.toml"

[[cohorts]]
name = "tp53_combined_external_validation"
role = "external_test"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/tp53_combined_external.toml"

[[cohorts]]
name = "pten_combined_external_validation"
role = "external_test"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/pten_combined_external.toml"

[[cohorts]]
name = "msh2_combined_external_validation"
role = "external_test"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/msh2_combined_external.toml"

[[cohorts]]
name = "kras_combined_external_validation"
role = "external_test"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/kras_combined_external.toml"

[[cohorts]]
name = "gck_combined_external_validation"
role = "external_test"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/gck_combined_external.toml"

[[cohorts]]
name = "f9_combined_external_validation"
role = "external_test"
source_config = "C:/Users/Wesley Capucho/Documents/IA dos números primos/primevarclass_multigene_real_benchmark_results/configs/f9_combined_external.toml"
